
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.graficasapp.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 52;
  public static final int LINEA_ESTILO = 31;
  public static final int PALABRA_CLAVE = 12;
  public static final int CHART = 9;
  public static final int Y = 25;
  public static final int DESCRIPCION = 11;
  public static final int X = 24;
  public static final int TIPO = 49;
  public static final int PUNTO_Y_COMA = 46;
  public static final int NOMBRE = 28;
  public static final int CORCHETE_I = 4;
  public static final int LLAVE_I = 2;
  public static final int PIE = 14;
  public static final int DOS_PUNTOS = 6;
  public static final int CORCHETE_D = 5;
  public static final int LLAVE_D = 3;
  public static final int FONDO = 16;
  public static final int FOR = 34;
  public static final int DATA = 8;
  public static final int IDENTIFICADOR = 51;
  public static final int IGUAL = 40;
  public static final int TITULO = 10;
  public static final int TAMANIO_FUENTE = 18;
  public static final int IF = 32;
  public static final int CATEGORIA = 21;
  public static final int EOF = 0;
  public static final int PALABRA = 50;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int ENCABEZADO = 13;
  public static final int PIXEL = 47;
  public static final int MENOR = 43;
  public static final int NO_IGUAL = 39;
  public static final int COLOR = 27;
  public static final int MAYOR = 41;
  public static final int DOBLE_IGUAL = 38;
  public static final int TAMANIO = 23;
  public static final int PUNTOS = 29;
  public static final int PARENTESIS_I = 36;
  public static final int VALOR = 26;
  public static final int ELSE = 33;
  public static final int PARENTESIS_D = 37;
  public static final int POSICION = 30;
  public static final int WHILE = 35;
  public static final int MAYOR_IGUAL = 42;
  public static final int COPYRIGHT = 15;
  public static final int NUMERO_COLOR = 48;
  public static final int MENOR_IGUAL = 44;
  public static final int LABEL = 22;
  public static final int X_BARRA = 19;
  public static final int Y_BARRA = 20;
  public static final int MAS = 45;
  public static final int FUENTE = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_I",
  "LLAVE_D",
  "CORCHETE_I",
  "CORCHETE_D",
  "DOS_PUNTOS",
  "COMA",
  "DATA",
  "CHART",
  "TITULO",
  "DESCRIPCION",
  "PALABRA_CLAVE",
  "ENCABEZADO",
  "PIE",
  "COPYRIGHT",
  "FONDO",
  "FUENTE",
  "TAMANIO_FUENTE",
  "X_BARRA",
  "Y_BARRA",
  "CATEGORIA",
  "LABEL",
  "TAMANIO",
  "X",
  "Y",
  "VALOR",
  "COLOR",
  "NOMBRE",
  "PUNTOS",
  "POSICION",
  "LINEA_ESTILO",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "PARENTESIS_I",
  "PARENTESIS_D",
  "DOBLE_IGUAL",
  "NO_IGUAL",
  "IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "MENOR",
  "MENOR_IGUAL",
  "MAS",
  "PUNTO_Y_COMA",
  "PIXEL",
  "NUMERO_COLOR",
  "TIPO",
  "PALABRA",
  "IDENTIFICADOR",
  "NUMERO"
  };
}

